CREATE TABLE `category` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(64) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE `product` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`category_id` INT(11),
	`name` VARCHAR(64) NOT NULL,
	`detail` TEXT,
	`price` INT(11) NOT NULL,
	`img` VARCHAR(64),
	PRIMARY KEY (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
